# Generated by Django 6.0.1 on 2026-01-28 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('xp_to_next_level', models.PositiveIntegerField(default=100)),
                ('dev_score', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('E', 'Новичок'), ('D', 'Junior'), ('C', 'Junior+'), ('B', 'Middle'), ('A', 'Middle+'), ('S', 'Senior')], default='E', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User stats',
                'verbose_name_plural': 'User stats',
            },
        ),
    ]
