# Generated by Django 6.0.1 on 2026-01-28 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'Статистика героя', 'verbose_name_plural': 'Статистика героя'},
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('workout', 'Тренировка'), ('task_complete', 'Завершение задачи'), ('skill_level_up', 'Повышение уровня навыка'), ('skill_mastered', 'Навык освоен'), ('learning_log', 'Запись обучения'), ('focus_session', 'Сессия фокуса'), ('github_commit', 'GitHub commit'), ('github_pr', 'GitHub PR')], max_length=32)),
                ('amount', models.IntegerField()),
                ('source_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=128)),
                ('source_url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие опыта',
                'verbose_name_plural': 'События опыта',
                'indexes': [models.Index(fields=['user', 'created_at'], name='stats_xpeve_user_id_41b9cc_idx'), models.Index(fields=['user', 'kind', 'created_at'], name='stats_xpeve_user_id_6e5720_idx'), models.Index(fields=['user', 'source_type', 'source_id'], name='stats_xpeve_user_id_746b5b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('source_type', ''), _negated=True), models.Q(('source_id', ''), _negated=True)), fields=('user', 'source_type', 'source_id'), name='uniq_xp_event_source_per_user')],
            },
        ),
    ]
