# Generated by Django 6.0.1 on 2026-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_userstats_options_xpevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='agility',
            field=models.PositiveIntegerField(default=1, verbose_name='Ловкость'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='intelligence',
            field=models.PositiveIntegerField(default=1, verbose_name='Интеллект'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='stat_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Свободные очки'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='strength',
            field=models.PositiveIntegerField(default=1, verbose_name='Сила'),
        ),
        migrations.AddField(
            model_name='userstats',
            name='vitality',
            field=models.PositiveIntegerField(default=1, verbose_name='Выносливость'),
        ),
    ]
