# Generated by Django 6.0.1 on 2026-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_userstats_agility_userstats_intelligence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpevent',
            name='kind',
            field=models.CharField(choices=[('workout', 'Тренировка'), ('task_complete', 'Завершение задачи'), ('skill_level_up', 'Повышение уровня навыка'), ('skill_mastered', 'Навык освоен'), ('learning_log', 'Запись обучения'), ('focus_session', 'Сессия фокуса'), ('boss_defeat', 'Победа над боссом'), ('github_commit', 'GitHub commit'), ('github_pr', 'GitHub PR')], max_length=32),
        ),
    ]
