# Generated by Django 6.0.1 on 2026-01-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('paused', 'Пауза'), ('done', 'Завершён')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('daily', 'Ежедневный'), ('main', 'Основной'), ('internship', 'Стажировка')], default='main', max_length=16),
        ),
    ]
