# Generated by Django 6.0.1 on 2026-01-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0004_seed_backend_skill_tree'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('coding', 'Кодинг'), ('learning', 'Обучение'), ('debugging', 'Отладка'), ('reading', 'Чтение документации'), ('review', 'Код-ревью'), ('interview', 'Подготовка к собеседованию')], default='coding', max_length=16)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='skills.skillnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фокус-сессия',
                'verbose_name_plural': 'Фокус-сессии',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='focus_focus_user_id_286337_idx'), models.Index(fields=['user', 'ended_at'], name='focus_focus_user_id_44cec9_idx'), models.Index(fields=['user', 'canceled', 'ended_at'], name='focus_focus_user_id_7c0545_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('canceled', False)), fields=('user',), name='uniq_active_focus_session_per_user')],
            },
        ),
    ]
