# Generated by Django 6.0.1 on 2026-01-28 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0004_alter_xpevent_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BossRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rank', models.CharField(default='E', max_length=32)),
                ('hp_max', models.PositiveIntegerField(default=1000)),
                ('hp_current', models.PositiveIntegerField(default=1000)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('defeated', 'Побеждён')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('defeated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Босс (забег)',
                'verbose_name_plural': 'Боссы (забеги)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BossDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xp_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss_damage', to='stats.xpevent')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='raids.bossrun')),
            ],
            options={
                'verbose_name': 'Урон боссу',
                'verbose_name_plural': 'Урон боссу',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bossrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='uniq_active_boss_per_user'),
        ),
    ]
