# Generated by Django 6.0.1 on 2026-01-28 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'category', 'name')},
        ),
    ]
