# Generated by Django 6.0.1 on 2026-01-28 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_unique_together_skill_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Трек навыков',
                'verbose_name_plural': 'Треки навыков',
                'ordering': ['order', 'title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='mastery_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('learning', 'Изучаю'), ('practicing', 'Практикую'), ('mastered', 'Освоено')], default='learning', max_length=16),
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('max_level', models.PositiveIntegerField(default=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='skills.skillnode')),
            ],
            options={
                'verbose_name': 'Узел навыка',
                'verbose_name_plural': 'Узлы навыков',
                'ordering': ['track__order', 'track__title', 'order', 'title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_skills', to='skills.skillnode'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(condition=models.Q(('node__isnull', False)), fields=('user', 'node'), name='uniq_skill_node_per_user'),
        ),
        migrations.AddField(
            model_name='skillnode',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='skills.skilltrack'),
        ),
    ]
