# Generated by Copilot on 2026-01-28

from __future__ import annotations

from django.db import migrations


def seed_backend_skill_tree(apps, schema_editor):
	SkillTrack = apps.get_model("skills", "SkillTrack")
	SkillNode = apps.get_model("skills", "SkillNode")

	tracks = [
		("django", "Django", 10),
		("drf", "DRF", 20),
		("database", "Базы данных", 30),
		("infra", "Инфраструктура", 40),
		("testing", "Тестирование", 50),
		("security", "Безопасность", 60),
		("architecture", "Архитектура", 70),
	]

	track_by_code = {}
	for code, title, order in tracks:
		obj, _ = SkillTrack.objects.get_or_create(code=code, defaults={"title": title, "order": order})
		# если уже есть — обновим порядок/заголовок (мягко)
		updated = False
		if obj.title != title:
			obj.title = title
			updated = True
		if obj.order != order:
			obj.order = order
			updated = True
		if updated:
			obj.save(update_fields=["title", "order"])
		track_by_code[code] = obj

	nodes = [
		(
			"django_basics",
			"Django основы",
			"Модели, миграции, ORM, админка, настройки.",
			"django",
			10,
			[],
		),
		(
			"django_auth",
			"Аутентификация и права",
			"Custom User, permissions, middleware, security basics.",
			"django",
			20,
			["django_basics"],
		),
		(
			"drf_basics",
			"DRF основы",
			"ViewSet, Serializer, pagination, permissions.",
			"drf",
			10,
			["django_basics"],
		),
		(
			"drf_auth",
			"DRF Auth (Token/JWT)",
			"TokenAuth/JWT, refresh, best practices.",
			"drf",
			20,
			["drf_basics", "django_auth"],
		),
		(
			"postgres",
			"PostgreSQL",
			"Индексы, EXPLAIN, транзакции, оптимизация запросов.",
			"database",
			10,
			[],
		),
		(
			"redis",
			"Redis",
			"Кеш, pub/sub, rate-limit, очереди (базово).",
			"infra",
			10,
			[],
		),
		(
			"celery",
			"Celery",
			"Очереди задач, retries, schedules, идемпотентность.",
			"infra",
			20,
			["redis"],
		),
		(
			"docker",
			"Docker",
			"Dockerfile, compose, multi-stage, best practices.",
			"infra",
			30,
			[],
		),
		(
			"ci_cd",
			"CI/CD",
			"Тесты, линт, сборка, деплой, миграции.",
			"infra",
			40,
			["docker"],
		),
		(
			"pytest",
			"Pytest + тестирование API",
			"Unit/Integration, fixtures, DRF APIClient.",
			"testing",
			10,
			[],
		),
		(
			"perf",
			"Профилирование и производительность",
			"N+1, кеширование, профилирование, нагрузка.",
			"architecture",
			10,
			["postgres", "drf_basics"],
		),
		(
			"owasp",
			"OWASP для backend",
			"XSS/CSRF/SSRF, injection, headers, секреты.",
			"security",
			10,
			["django_auth"],
		),
	]

	node_by_code = {}
	for code, title, description, track_code, order, prereq_codes in nodes:
		track = track_by_code[track_code]
		obj, _ = SkillNode.objects.get_or_create(
			code=code,
			defaults={
				"track": track,
				"title": title,
				"description": description,
				"order": order,
				"max_level": 100,
			},
		)
		# мягкое обновление
		updated = False
		if obj.track_id != track.id:
			obj.track = track
			updated = True
		if obj.title != title:
			obj.title = title
			updated = True
		if obj.description != description:
			obj.description = description
			updated = True
		if obj.order != order:
			obj.order = order
			updated = True
		if updated:
			obj.save(update_fields=["track", "title", "description", "order"])
		node_by_code[code] = obj

	# Пререквизиты
	for code, _, _, _, _, prereq_codes in nodes:
		obj = node_by_code[code]
		if prereq_codes:
			obj.prerequisites.set([node_by_code[p].id for p in prereq_codes])


def unseed_backend_skill_tree(apps, schema_editor):
	# Не удаляем данные автоматически (пользователь мог уже привязать прогресс).
	pass


class Migration(migrations.Migration):
	dependencies = [
		("skills", "0003_skilltrack_skill_mastery_xp_alter_skill_status_and_more"),
	]

	operations = [
		migrations.RunPython(seed_backend_skill_tree, unseed_backend_skill_tree),
	]
