# Generated by Django 6.0.1 on 2026-01-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, default='', max_length=128)),
                ('how_to_address', models.CharField(blank=True, default='', help_text="Как ассистент должен к тебе обращаться (например: 'Нурс', 'господин Нурсултан', 'брат').", max_length=128)),
                ('about_me', models.TextField(blank=True, default='', help_text='Факты о тебе, которые можно использовать в ответах')),
                ('assistant_persona', models.TextField(blank=True, default='', help_text='Характер/стиль ассистента (тон, краткость, правила общения).')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль ИИ',
                'verbose_name_plural': 'Профили ИИ',
            },
        ),
    ]
